spring:
  docker:
    compose:
      enabled: true
      file: ./docker/compose.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/reportapp
    username: myuser
    password: secret

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE