apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportapp
  labels:
    app: reportapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportapp
  template:
    metadata:
      name: reportapp
      labels:
        app: reportapp
    spec:
      containers:
        - name: reportapp
          image: docker.io/example/reportapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: reportapp-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: reportapp-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reportapp-secret
                  key: DB_PASSWORD

      restartPolicy: Always
      